#!/bin/bash

set -e

# GRANT USAGE, CREATE ON SCHEMA public TO $PG_USERNAME; 

psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER_USERNAME" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "${PG_USERNAME}" WITH PASSWORD '${PG_PASSWORD}';
  CREATE DATABASE ${PG_DATABASE} OWNER ${PG_USERNAME};
  GRANT ALL PRIVILEGES ON DATABASE ${PG_DATABASE} TO ${PG_USERNAME};
  \c ${PG_DATABASE};
  GRANT ALL PRIVILEGES ON SCHEMA public TO ${PG_USERNAME};
EOSQL