services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    hostname: ${PG_HOST}
    environment:
      POSTGRES_USER: ${PG_SUPERUSER_USERNAME}
      POSTGRES_PASSWORD: ${PG_SUPERUSER_PASSWORD}
    volumes:
      - './src/db/init:/docker-entrypoint-initdb.d/'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"']
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    restart: always
    hostname: naself-redis
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8090:8080
