services:
  api:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
      - .:/app
      - /home/maek/Documents:/data
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    hostname: ${PG_HOST}
    environment:
      POSTGRES_USER: ${PG_SUPERUSER_USERNAME}
      POSTGRES_PASSWORD: ${PG_SUPERUSER_PASSWORD}
    volumes:
      - './src/db/init:/docker-entrypoint-initdb.d/'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"']
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    restart: always
    hostname: naself-redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8090:8080
